### DISCUSSION TITLE
TF 22.01.24

### DISCUSSION THREAD

**Discussion by andreaa93** [FAIRmat-NFDI/AreaA-data_modeling_and_schemas#105] [Task Force Meeting]
Some classes to discuss:

Entities:

* MeasurementInstrument  
  * InstrumentParts
    * take from NeXus
* ProcessInstrument  
  * InstrumentParts
    * furnace (instrument description)
    * sources (instrument description)
      * bubbler
      * flash evaporator
      * gas cylinder
    * crucible (instrument features)

Activties:

* MaintenanceActivity  (on Instruments, or InstrumentParts)
* Process:
  * SetParameters (find a name for this list of settings)
    * furnace (process parameters)
    * sources (process parameters)
* Mixture preparation
  * solution preparation.
  * powder preparation.
    (look at CaP synthesis)
    (look at weighing in DS)

@budschi thia can be dropped in the announcing email of TF

**Comment by andreaa93** [comment]
Classes to add in plugins:

```
Instrument: (or InstrumentPart)
  production_date:
  installation_date:
  working_hours:
  nominal_lifetime:
  activity:
    - calibration
    - cleaning
    - maintenance
    - repair
    - replacement
    - pretreatment

Furnace(Instrument):
  name:
  model:
  furnace_id:
  Manufacturer:
  geometry: 
    Shape: The geometry of the furnace.
    Furnace_Diameter:
  material: The material the furnace is made of.
  furnace_description:

Crucible(Instrument):
  crucible_id:
  crucible_weight:
  crucible_model:
  crucible_coating:
  crucible_coating_pretreatment:  (Activity ref)
  support_side_and_bottom_shape:
  top_cover:
  top_cover_material:
  top_cover_age:
  crucible_model:
  crucible_weight_grams:
  crucible_coating: "VESUVIUS producer. Coated at IKZ with HC Stark"
  crucible_coating_preparation: (Activity ref)

Heating(Instrument):
  The heating type of the furnace.
  Type: resistance / induction
  Manufacturer: 
  HeaterPower:

Mixture preparation
  solution preparation.
  powder preparation: 
    - (look at CaP synthesis)
    - (look at weighing in DS)
```

To discuss Further:

- the overlap of info in the Instrument(Entity) and Process(Activity): setup and settings of the instrument
- check against some example (PVD, MOVPE)

```
Process(Activity):
  Instrument(Entity): references
    - Parts:
        Shutter: ON/OFF (show it also in process)
  Instrument_settings: (can be time dependent or time independent)
    Parts: ( with or without Steps)
        SetupGeometry:
          The geometry arrangement of the Instrument (shower head distance)
        SampleGeometry:
          The geometry arrangement, e.g., the substrate position in the chamber.
        SetParameters[*]:
        RecordedParameters[*]:
  Results: (check overlap between RecordedParameters and results!! make a decision on where to place info and how to split it)
```
@budschi @hampusnasstrom

 @RoteKekse we would like to discuss sometimes and exchange on the Settings piece of info. What goes in Instrument what in Process
