### ISSUE TITLE
Base_classes updates: verify is each schema has these features 

### ISSUE THREAD

**Issue by aalbino2** [FAIRmat-NFDI/AreaA-data_modeling_and_schemas#10]
when designing schemas, I'm adding new features to the base_classes file that need to be harmonized in __all__ the examples:

This is a checklist that should be scrolled down before releasing a schema.  

- [ ] global class as subsection in activity
- [ ] take care around of the sampleid 
- [ ] the instrument is placed into Activity(Workflow). So every task in the "tasks" list will have the possibility to instance an instrument (instrument might be treated as a generic input in future)
- [ ] publication reference added into the schemas. So far, I used it into the "Global" subsection contained into "Activity"
  ```
      sub_sections:
        publication_reference:
          repeats: True
          m_annotations:
            eln:
          section: nomad.datamodel.metainfo.eln.PublicationReference
  ```
- [ ] add the new Tabular feature merged by Amir: https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/issues/1243
- [ ] change inheritance of Task, TaskReference, Workflow, Link, ElnBaseSection
- [ ] use the System Ensemble and Component classes available at /nomad-FAIR/nomad/datamodel/metainfo/eln/__init__.py
- [ ] check that EntryData is not stated twice (EntryData classes are Entity and Experiment)
- [ ] all "timestamp" should be changed in "datetime" (from ElnBaseSection)
- [ ] all "notes" in "description" (from ElnBaseSection)
